#!/bin/sh

sed -i "/ace/d" /etc/opkg/distfeeds.conf
sed -i "/passwall_packages/d" /etc/opkg/distfeeds.conf
sed -i "/passwall/d" /etc/opkg/distfeeds.conf
sed -i "/passwall2/d" /etc/opkg/distfeeds.conf
sed -i 's,downloads.immortalwrt.org,mirrors.vsean.net/openwrt,g' /etc/opkg/distfeeds.conf

# firewall
uci batch <<EOF
delete firewall.@defaults[0].syn_flood='0'
delete firewall.@zone[0].network
add_list firewall.@zone[0].network='lan'
add_list firewall.@zone[0].network='lan6'
EOF
uci commit firewall
/etc/init.d/firewall restart

# network config
uci batch <<EOF
delete network.lan.ip6assign
delete network.globals.ula_prefix
set network.lan6=interface
set network.lan6.proto='dhcpv6'
set network.lan6.device='@lan'
set network.lan6.reqaddress='try'
set network.lan6.reqprefix='auto'
EOF
uci commit network
/etc/init.d/network restart

uci -q batch <<-EOF
        set system.@system[0].timezone='CST-8'
        set system.@system[0].zonename='Asia/Shanghai'

        delete system.ntp.server
        add_list system.ntp.server='cn.ntp.org.cn'
        add_list system.ntp.server='edu.ntp.org.cn'
        add_list system.ntp.server='ntp.ntsc.ac.cn'
        add_list system.ntp.server='ntp.tuna.tsinghua.edu.cn'
EOF
uci commit system

exit 0
