#!/bin/sh

# luci language
uci set luci.main.lang=zh_cn
uci commit luci

# argon
uci batch <<EOF
set argon.@global[0].primary='#1c78ff'
set argon.@global[0].dark_primary='#1c78ff'
set argon.@global[0].blur='10'
set argon.@global[0].blur_dark='10'
set argon.@global[0].transparency='0.5'
set argon.@global[0].transparency_dark='0.5'
set argon.@global[0].mode='normal'
set argon.@global[0].online_wallpaper='none'
EOF
uci commit argon

# ttyd autologin
#sed -i '65s/^#//g' /etc/init.d/ttyd
#uci set ttyd.@ttyd[0].interface='@lan'
#uci set ttyd.@ttyd[0].command='/bin/login -f root'
#uci commit ttyd
#/etc/init.d/ttyd restart

# turboacc
#uci batch <<EOF
#set turboacc.config.bbr_cca='1'
#set turboacc.config.fullcone6='0'
#set turboacc.config.hw_wed='0'
#EOF
#uci commit turboacc


# netspeedtest homebox is on
# uci set netspeedtest.homebox.enabled='1'
# uci set netspeedtest.speedtestiperf3.enabled='1'
# uci commit netspeedtest

# system
uci batch <<EOF
set system.@system[0].hostname='Bypass.Router'
set system.@system[0].timezone='PST8PDT,M3.2.0,M11.1.0'
set system.@system[0].zonename='America/Los Angeles'
delete system.ntp.enable_server
add_list system.ntp.server="cn.ntp.org.cn"
add_list system.ntp.server="edu.ntp.org.cn"
add_list system.ntp.server="ntp.ntsc.ac.cn"
add_list system.ntp.server="ntp.tuna.tsinghua.edu.cn"
set system.ntp.use_dhcp='0'
EOF
uci commit system

# fix distfeeds
sed -i "/ace8/d" /etc/opkg/distfeeds.conf
sed -i "/passwall_packages/d" /etc/opkg/distfeeds.conf
sed -i "/passwall/d" /etc/opkg/distfeeds.conf
sed -i "/passwall2/d" /etc/opkg/distfeeds.conf
sed -i "/mosdns/d" /etc/opkg/distfeeds.conf
sed -i "/netspeedtest/d" /etc/opkg/distfeeds.conf

# firewall
uci batch <<EOF
delete firewall.@defaults[0].syn_flood='0'
set firewall.@defaults[0].input='ACCEPT'
set firewall.@defaults[0].forward='ACCEPT'
set firewall.@defaults[0].fullcone6='1'
delete firewall.@zone[0].network
add_list firewall.@zone[0].network='lan'
add_list firewall.@zone[0].network='lan6'
add_list firewall.@zone[0].network='lan2'
add_list firewall.@zone[0].network='lan3'
EOF
uci commit firewall
/etc/init.d/firewall restart

# dnsmasq
uci batch <<EOF
delete dhcp.@dnsmasq[0].boguspriv
delete dhcp.@dnsmasq[0].filterwin2k
delete dhcp.@dnsmasq[0].authoritative
delete dhcp.@dnsmasq[0].readethers
delete dhcp.@dnsmasq[0].resolvfile
delete dhcp.@dnsmasq[0].nonwildcard
delete dhcp.@dnsmasq[0].filter_a
set dhcp.@dnsmasq[0].nonegcache='1'
set dhcp.@dnsmasq[0].cachesize='10000'
set dhcp.@dnsmasq[0].filter_aaaa='1'
set dhcp.@dnsmasq[0].server='127.0.0.1#5335'
set dhcp.@dnsmasq[0].noresolv='1'
set dhcp.@dnsmasq[0].nohosts='1'
set dhcp.@dnsmasq[0].serversfile='/etc/dnsmasq.d/accelerated-domains.china.conf'
delete dhcp.lan.dhcpv6
delete dhcp.lan.ra
delete dhcp.lan.ra_slaac
delete dhcp.lan.ra_flags
delete dhcp.lan.ndp
set dhcp.lan.ignore='1'
set dhcp.lan.dynamicdhcp='0'
EOF
uci commit dhcp
/etc/init.d/dnsmasq restart

# network config
uci batch <<EOF
delete network.lan.ip6assign
delete network.globals.ula_prefix
set network.globals.packet_steering='1'
set network.lan.gateway='192.168.177.1'
set network.lan.dns='127.0.0.1'
set network.lan6=interface
set network.lan6.proto='dhcpv6'
set network.lan6.device='@lan'
set network.lan6.reqaddress='try'
set network.lan6.reqprefix='auto'
set network.lan2=interface
set network.lan2.proto='static'
set network.lan2.device='br-lan'
set network.lan2.ipaddr='192.168.177.78'
set network.lan2.netmask='255.255.255.0'
set network.lan2.gateway='192.168.177.1'
set network.lan2.metric='40'
set network.lan2.dns='127.0.0.1'
set network.lan3=interface
set network.lan3.proto='static'
set network.lan3.device='br-lan'
set network.lan3.ipaddr='192.168.177.79'
set network.lan3.netmask='255.255.255.0'
set network.lan3.gateway='192.168.177.1'
set network.lan3.dns='127.0.0.1'
set network.lan3.metric='40'
EOF
uci commit network
/etc/init.d/network restart

# dnscrypt-proxy2 setting
sed -i 's/START=18/START=99/g' /etc/init.d/dnscrypt-proxy
sed -i 's/127.0.0.53:53/127.0.0.1:5335/g' /etc/dnscrypt-proxy2/dnscrypt-proxy.toml
sed -i 's/ipv6_servers = false/ipv6_servers = true/g' /etc/dnscrypt-proxy2/dnscrypt-proxy.toml
sed -i 's/odoh_servers = false/odoh_servers = true/g' /etc/dnscrypt-proxy2/dnscrypt-proxy.toml
sed -i 's/http3 = false/http3 = true/g' /etc/dnscrypt-proxy2/dnscrypt-proxy.toml
sed -i 's/cache_size = 4096/cache_size = 10240/g' /etc/dnscrypt-proxy2/dnscrypt-proxy.toml
sed -i 's/127.0.0.1:9050/127.0.0.1:1070/g' /etc/dnscrypt-proxy2/dnscrypt-proxy.toml
sed -i 's/127.0.0.1:8888/127.0.0.1:1101/g' /etc/dnscrypt-proxy2/dnscrypt-proxy.toml
#sed -i 's/# proxy/proxy/g' /etc/dnscrypt-proxy2/dnscrypt-proxy.toml
#sed -i 's/# http_proxy/http_proxy/g' /etc/dnscrypt-proxy2/dnscrypt-proxy.toml
#sed -i 's/# blocked_names_file/blocked_names_file/g' /etc/dnscrypt-proxy2/dnscrypt-proxy.toml

# crontabs
echo '* 4 * * 1  wget --no-check-certificate -O /etc/dnsmasq.d/accelerated-domains.china.conf "https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf"' >> /etc/crontabs/root

exit 0
reboot
