#!/bin/bash

# syncdial
uci -q batch <<-EOF
  set syncdial.config=syncdial
  set syncdial.config.syncon='1'
  set syncdial.config.dialwait='25'
  set syncdial.config.dialchk='0'
  set syncdial.config.nomwan='1'
  set syncdial.config.wanselect='wan'
  set syncdial.config.dial_type='1'
  set syncdial.config.wannum='3'
  set syncdial.config.dialnum='3'
  set syncdial.config.old_frame='1'
  set syncdial.config.devbackup='wan'
  set syncdial.config.bindwan='0'
  set syncdial.config.enabled='1'
  commit syncdial
EOF
bash /bin/genwancfg

#/etc/init.d/dropbear stop
#/etc/init.d/passwall2 stop
#/etc/init.d/udp2raw stop
#/etc/init.d/tailscale stop

#sysupgrade -r /etc/backup/Xiaomi_MI_R3G_us_lanx2.tar.gz
#rm -rf /etc/backup

#uci commit system
#uci commit network
#/etc/init.d/network restart
#uci commit dhcp
#/etc/init.d/dnsmasq restart
#uci commit mosdns
#uci commit argon

#/etc/init.d/passwall2 start
#/etc/init.d/udp2raw start
#/etc/init.d/tailscale start
#sleep 20
#uci commit firewall
#/etc/init.d/firewall restart
#/etc/init.d/dropbear start

exit 0
