#!/bin/bash

/etc/init.d/dropbear stop
/etc/init.d/passwall2 stop
/etc/init.d/udp2raw stop
/etc/init.d/tailscale stop

#sysupgrade -r /etc/backup/Xiaomi_MI_R3G_us_lanx2.tar.gz
#rm -rf /etc/backup

uci commit system
uci commit network
/etc/init.d/network restart
uci commit dhcp
/etc/init.d/dnsmasq restart
uci commit mosdns
uci commit argon

/etc/init.d/passwall2 start
/etc/init.d/udp2raw start
/etc/init.d/tailscale start
sleep 20
uci commit firewall
/etc/init.d/firewall restart
/etc/init.d/dropbear start

exit 0
